services:
  db:
    image: postgres:16
    container_name: verisafe_db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5449:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - verinet
  app:
    image: opencrafts/verisafe-backend-staging:dev
    container_name: verisafe-container
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - .env:/workspace/.env
    networks:
      - verinet
      - rabbitmq-shared
volumes:
  db_data:
networks:
  verinet:
  rabbitmq-shared:
    external: true