services:
  db:
    image: postgres:16
    container_name: verisafe_db
    restart: unless-stopped
    env_file: .env
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    ports:
      - "5449:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    image: opencrafts/verisafe-backend-staging:dev
    container_name: verisafe
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3003:8080"
    env_file: .env
    volumes:
      - .env:/workspace/.env
volumes:
  db_data:
