services:
  db:
    image: postgres:16
    container_name: keep-up_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${DB_PORT_HOST}:5432"
    volumes:
      - keepup_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: opencrafts/keep-up-staging:dev
    container_name: keep-up_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${APP_PORT_HOST}:8000"
    volumes:
      - .env:/workspace/.env

volumes:
  db_data:
